title: Luisana Guaita # your name (or website title) here
logo: "/images/Photo_L.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Civil engineer and data science master's student with +8 years of experience in project engineering, making reports, drafting, and +3 years of teaching mathematics and statistics, specifically catering to the Cambridge syllabus.
  <br>
  Leader of the Go Green Committee at TIPS. Responsible for the 1st Summer School based on Sustainability and STEM.
  <br><br>
  <a href="https://www.linkedin.com/in/luisanaguaita/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
