title: Luisana Guaita # your name (or website title) here
<img src="/images/Photo_L.jpg?raw=true" alt="Logo" style="border-radius: 50%; width: 150px; height: 150px;">
#logo: "/images/Photo_L.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Experienced civil engineer and data science master's student with expertise in project engineering, report writing, and teaching mathematics $ statistics.
  <br><br>
  Leader of the Go Green Committee and organizer of the first Summer School on sustainability and STEM at TIPS.
  <br><br>

  <a href="https://www.linkedin.com/in/luisanaguaita/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here





